### ISSUE TITLE
How to run validations check  before opening up the stripe popup ?

### ISSUE THREAD

**Issue by Gururaj26** [azmenak/react-stripe-checkout#121]
Markup
```
<StripeCheckout token={this.token} stripeKey={process.env.REACT_APP_STRIPE_API_KEY}>
      <button className="btn btn-elf-primary btn-block">Checkout</button>
</StripeCheckout>
```

Action on token

```
onToken = (token) => {
   if(this.isValid()){
     // expecting popup to open when all the fields are valid
  }
}
```

**Comment by cheong12001** [comment]
Yes, i also have the same question with you.

**Comment by cheong12001** [comment]
i have solved by hidden the stripeCheckout component and assign the button inside stripeCheckout library a reference. first click on another button to do validation, after the validation, call reference.click() to proceed the stripe checkout procedure.

**Comment by danielpgross** [comment]
This worked for me:
```
<StripeCheckout
  ...
>
  <button
    ...
    onClick={(e) => {
      let isValid = this.billingAddrFormRef.current.reportValidity();
      if (!isValid) {
        e.stopPropagation(); 
      }
    }}
  >
    Pay with Credit Card
  </button>
</StripeCheckout>
```

**Comment by usamamashkoor** [comment]
@danielpgross can you please explain more how did you assign reference in react.?

I want to do the same validate the form data and then open the Stripe Handler.

**Comment by dark-swordsman** [comment]
@usamamashkoor Just came across this. Hopefully this can help others.

`reportValidity()` is a DOM Element method: https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/reportValidity

People seem to confuse DOM Elements with React Components: https://stackoverflow.com/questions/42242146/react-how-to-access-the-dom-element-in-my-render-function-from-the-same-compone

Doing `ref` works in cases where you need to do react stuff on a component. However, in this case since reportValidity is a DOM element method and ref only returns an object, not a DOM element, we have to do it in a seemingly non-react way.

This way worked for me:

```js
<Button color="success" size="lg" type="button" onClick={(e) => {
  const ticketForm = document.getElementById('ticketForm');
  const isValid = ticketForm.reportValidity();
  if (!isValid) e.stopPropagation();
}}>Buy Tickets</Button>
```
