### ISSUE TITLE
support for disabling click

### ISSUE THREAD

**Issue by mderazon** [azmenak/react-stripe-checkout#13]
Sometimes when filling forms, you'd want to disable hitting the "submit" button until form is complete.

Since react-stripe-checkout wraps the button element (or any other element) and adds a click handler, it's hard to disable it.

I propose to add a new attribute `disabled` that, when true, will just disable the click handler.

Please let me know what you think, i'll be happy to send a PR

:cookie:

**Comment by mderazon** [comment]
Forget about it, I can just use an `onClick` in the wrapped component and just do `stopPropagation`.

Sorry and thanks 
:cookie:

**Comment by ADumaine** [comment]
I have the same issue. The component should be disabled until a quantity is entered.

In my case I have a custom button is disabled based on state, but the whole div the component generates is still clickable and brings up the stripe widget.

I have tried the `event.stopPropagation()` in the onClick of the wrapper, but that is not stopping it (Chrome 47 and IE 11)

@mderazon (or anyone else) would you post an example of how you got it to work?

**Comment by mderazon** [comment]
Not sure what it didn't work for you, but this worked for me
``` jsx
onSubmit = (event) => {
  // in case the form is not valid, just don't call StripeCheckout
  if (!this.state.valid) {
    return event.stopPropagation()
  }
  // ...
}

<StripeCheckout
  token={this.onToken}
  stripeKey='key' >
  <Button enabled={this.state.valid} onClick={this.onSubmit}>
    Click Me!
  </Button>
</StripeCheckout>
```

**Comment by ADumaine** [comment]
Thanks for the example. I have essentially the same thing but clicking anywhere on the component (left or right of the disabled button or the button itself) fires the event.  

I changed mine slightly to have the button always enabled and it does stop the event, but only if the button is clicked. 
```javascript
 handleQtyCheck: function (event) {
        if (!this.state.quantity) {
            console.log("QTY CHECK");
             return event.stopPropagation();
         };
    },
//.....
<div >
            <StripeCheckout token={this.onToken}
                            stripeKey={pubKey}
                             ...other items....
                           >
                            <Button type="button"
                                    inputClasses={{ 'btn-primary': true }}
                                    disabled={false}
                                   onClick={this.handleQtyCheck}>
                                Purchase             
                            </Button>
            </StripeCheckout>
            </div>
```
If the click is outside the button it still launches the widget.  Perhaps this is due to the bootstrap grid layout that causes the stripe component to stretch across the column with the button only filling the center portion of it.  The only thing I can think of doing at this point is resizing the component to smaller than the button.  I would much rather have the disabled property as you first suggested.

In StripeCheckout.jsx  it appears there is an onClick event bound to the component, not just the button.  I see how the button can stop the propagation, but what if you click just outside the button (but still on the component) in your implementation?

```javascript
render: function () {
    var ComponentClass = this.props.componentClass;
    return (
      !this.props.children ? this.renderStripeButton() : (
        <ComponentClass {...this.props} onClick={this.onClick}>
          {this.props.children}
        </ComponentClass>
      )
    );
  }
```

**Comment by azmenak** [comment]
@ADumaine the `onClick` even will only be added to the `<ComponentClass />` which doesn't get created if you passed any children in, so that shouldn't be an issue.

Maybe when you are checking `if (!this.state.quantity) { ...` there is a truthy value coming from the input. Eg. in js `!!"0"` becomes `true`.

**Comment by ADumaine** [comment]
@azmenak  even if I set the button disabled={true} I can click on the component to launch the widget.  I think the onClick is getting added even with children being passed in.  I just don't see how.

**Comment by jmsherry** [comment]
I think it's a pretty good idea. If your wrapped button is disabled then no onClick will occur on it, so you can't stopPropagation!
